generate components map
voltone/sbom pull request #4
Opened 2020-11-16 08:41 UTC by sigu

2020-11-24 06:38 UTC, voltone requested changes
Looking good, thanks! A few tiny change requests, and a suggestion for more robust testing, below...

2020-11-24 06:38 UTC, voltone commented on test/sbom/cyclonedx_test.exs
> +      assert json =~ "{\n  \"bomFormat\": \"CycloneDX\""
It seems a bit brittle to assert on a JSON literal with whitespace. I would prefer asserting that the result can be decoded by Jason, and then assert on values in the resulting map:

```elixir
  assert {:ok, decoded} = Jason.parse(json)
  assert decoded["bomFormat"] == "CycloneDX"
```

Same thing for the other JSON assertions in this file.

2020-11-24 06:38 UTC, voltone commented on lib/mix/tasks/sbom.cyclonedx.ex
> +      shell.error("Json is not supported in version 1.1")
```suggestion
      shell.error("JSON is not supported in version 1.1")
```

2020-11-24 06:38 UTC, voltone commented on lib/mix/tasks/sbom.cyclonedx.ex
> +      Mix.raise("JSON is NOT supported for version 1.1 of cyclonedx.")
```suggestion
      Mix.raise("JSON is NOT supported for version 1.1 of CycloneDX.")
```

2020-11-24 06:38 UTC, voltone commented on lib/sbom/cyclonedx.ex
> +  Generate a CycloneDX SBoM in XML and JSON format.
```suggestion
  Generate a CycloneDX SBoM in XML or JSON format.
```

2020-12-08 05:27 UTC, sigu commented
@voltone , these comments have been worked on, thanks to @TraceyOnim

2020-12-13 14:46 UTC, voltone commented
Thanks for the updates. I was going to test this with OWASP DependencyTrack 4.0 beta, but I ran into a few issues.

One is that the JSON encoder assumes all fields are present, but some component fields are not always available, so something like `component.description` might fail. That's easy enough to fix.

But more fundamentally, I prefer to install the SBoM Mix task globally, as an archive (`mix archive.install hex sbom`), rather than adding it as a project dependency. Unfortunately, such Mix tasks cannot rely on dependencies, so the Jason package is unavailable. Need to think about this: either we'd have to give up on using this as an archive (at least when JSON output is desired), or we add just enough JSON builder support, like we do for XML...

2022-03-02 06:44 UTC, sigu commented
I am closing this since we can use https://github.com/CycloneDX/cyclonedx-cli to convert to different formats

2022-03-02 06:44 UTC, closed without merging